spring:
  application:
    name: imperative-application
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password:
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

server:
  port: 8090
